<?
define("HIDE_SIDEBAR", true);
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Заказы");
?>
<? $APPLICATION->IncludeComponent(
    "bitrix:sale.order.ajax",
    'shop',
    Array(
        "ACTION_VARIABLE" => "soa-action",
        "ADDITIONAL_PICT_PROP_10" => "-",
        "ADDITIONAL_PICT_PROP_18" => "-",
        "ADDITIONAL_PICT_PROP_19" => "-",
        "ADDITIONAL_PICT_PROP_2" => "-",
        "ADDITIONAL_PICT_PROP_3" => "-",
        "ADDITIONAL_PICT_PROP_4" => "-",
        "ADDITIONAL_PICT_PROP_568" => "-",
        "ADDITIONAL_PICT_PROP_569" => "-",
        "ADDITIONAL_PICT_PROP_6" => "-",
        "ALLOW_APPEND_ORDER" => "Y",
        "NO_PERSONAL" => "Y",
        "ALLOW_AUTO_REGISTER" => "Y",
        "ALLOW_NEW_PROFILE" => "N",
        "ALLOW_USER_PROFILES" => "N",
        "BASKET_IMAGES_SCALING" => "adaptive",
        "BASKET_POSITION" => "after",
        "BRAND_PROPERTY" => "",
        "COMPATIBLE_MODE" => "N",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
        "COUNT_DELIVERY_TAX" => "N",
        "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
        "DATA_LAYER_NAME" => "dataLayer",
        "DELIVERIES_PER_PAGE" => "9",
        "DELIVERY_FADE_EXTRA_SERVICES" => "N",
        "DELIVERY_NO_AJAX" => "Y",
        "DELIVERY_NO_SESSION" => "Y",
        "DELIVERY_TO_PAYSYSTEM" => "d2p",
        "DISABLE_BASKET_REDIRECT" => "N",
        "EMPTY_BASKET_HINT_PATH" => SITE_DIR . "",
        "HIDE_ORDER_DESCRIPTION" => "N",
        "ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
        "PATH_TO_AUTH" => SITE_DIR . "personal/",
        "PATH_TO_BASKET" => SITE_DIR . "personal/cart/",
        "PATH_TO_ORDER" => SITE_DIR . "personal/order/make/",
        "PATH_TO_PAYMENT" => SITE_DIR . "personal/order/payment/",
        "PATH_TO_PERSONAL" => SITE_DIR . "personal/orders/",
        "PAY_FROM_ACCOUNT" => "Y",
        "PAY_SYSTEMS_PER_PAGE" => "9",
        "PICKUPS_PER_PAGE" => "5",
        "PICKUP_MAP_TYPE" => "yandex",
        "PRODUCT_COLUMNS_HIDDEN" => array(),
        "PRODUCT_COLUMNS_VISIBLE" => array("PREVIEW_PICTURE", "PROPS"),
        "PROPS_FADE_LIST_1" => array(),
        "PROPS_FADE_LIST_2" => "",
        "PROPS_FADE_LIST_5" => array(),
        "PROP_1" => "",
        "SEND_NEW_USER_NOTIFY" => "Y",
        "SERVICES_IMAGES_SCALING" => "adaptive",
        "SET_TITLE" => "Y",
        "SHOW_ACCOUNT_NUMBER" => "Y",
        "SHOW_BASKET_HEADERS" => "N",
        "SHOW_COUPONS_BASKET" => "N",
        "SHOW_COUPONS_DELIVERY" => "N",
        "SHOW_COUPONS_PAY_SYSTEM" => "N",
        "SHOW_DELIVERY_INFO_NAME" => "Y",
        "SHOW_DELIVERY_LIST_NAMES" => "Y",
        "SHOW_DELIVERY_PARENT_NAMES" => "Y",
        "SHOW_MAP_IN_PROPS" => "N",
        "SHOW_NEAREST_PICKUP" => "N",
        "SHOW_NOT_CALCULATED_DELIVERIES" => "Y",
        "SHOW_ORDER_BUTTON" => "final_step",
        "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
        "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
        "SHOW_PICKUP_MAP" => "Y",
        "SHOW_STORES_IMAGES" => "Y",
        "SHOW_TOTAL_ORDER_BUTTON" => "Y",
        "SHOW_VAT_PRICE" => "N",
        "SKIP_USELESS_BLOCK" => "Y",
        "SPOT_LOCATION_BY_GEOIP" => "Y",
        "TEMPLATE_LOCATION" => "popup",
        "TEMPLATE_THEME" => "blue",
        "USER_CONSENT" => "Y",
        "USER_CONSENT_ID" => "0",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "Y",
        "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
        "USE_CUSTOM_ERROR_MESSAGES" => "N",
        "USE_CUSTOM_MAIN_MESSAGES" => "N",
        "USE_ENHANCED_ECOMMERCE" => "Y",
        "USE_PHONE_NORMALIZATION" => "Y",
        "USE_PRELOAD" => "Y",
        "USE_PREPAYMENT" => "N",
        "USE_YM_GOALS" => "Y",
        "YM_GOALS_COUNTER" => "",
        "YM_GOALS_EDIT_BASKET" => "BX-basket-edit",
        "YM_GOALS_EDIT_DELIVERY" => "BX-delivery-edit",
        "YM_GOALS_EDIT_PAY_SYSTEM" => "BX-paySystem-edit",
        "YM_GOALS_EDIT_PICKUP" => "BX-pickUp-edit",
        "YM_GOALS_EDIT_PROPERTIES" => "BX-properties-edit",
        "YM_GOALS_EDIT_REGION" => "BX-region-edit",
        "YM_GOALS_INITIALIZE" => "BX-order-init",
        "YM_GOALS_NEXT_BASKET" => "BX-basket-next",
        "YM_GOALS_NEXT_DELIVERY" => "BX-delivery-next",
        "YM_GOALS_NEXT_PAY_SYSTEM" => "BX-paySystem-next",
        "YM_GOALS_NEXT_PICKUP" => "BX-pickUp-next",
        "YM_GOALS_NEXT_PROPERTIES" => "BX-properties-next",
        "YM_GOALS_NEXT_REGION" => "BX-region-next",
        "YM_GOALS_SAVE_ORDER" => "OK_ADDING"
    )
); ?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>
